---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
  namespace: &namespace renovate
spec:
  interval: 1h
  targetNamespace: *namespace
  path: ./kubernetes/apps/renovate/renovate-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate-operator
      namespace: renovate
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-jobs
  namespace: &namespace renovate
spec:
  dependsOn:
    - name: renovate-operator
  interval: 1h
  targetNamespace: *namespace
  path: ./kubernetes/apps/renovate/renovate-operator/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
