---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name renovate-operator
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Renovate Operator
    gethomepage.dev/icon: renovate.svg
    gethomepage.dev/pod-selector: app=renovate-operator
spec:
  hostnames:
    - renovate.tholinka.dev
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: *name
          namespace: renovate
          port: 8081
