---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-import
  namespace: &namespace network
spec:
  interval: 1h
  path: ./kubernetes/apps/network/certificates/import
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  healthChecks:
    - apiVersion: v1
      kind: Secret
      namespace: *namespace
      name: tholinka-dev-tls
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-export
  namespace: &namespace network
spec:
  dependsOn:
    - name: certificates-import
  interval: 1h
  path: ./kubernetes/apps/network/certificates/export
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  healthChecks:
    - apiVersion: &certApi cert-manager.io/v1
      kind: &certKind Certificate
      namespace: *namespace
      name: tholinka-dev
  healthCheckExprs:
    - apiVersion: *certApi
      kind: *certKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
