---
# yaml-language-server: $schema=https://schemas.tholinka.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tholinka-dev
spec:
  duration: 160h
  secretName: 'tholinka-dev-tls'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: tholinka.dev
  dnsNames:
    - tholinka.dev
    - '*.tholinka.dev'
  usages:
    - 'digital signature'
