---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: &namespace system
spec:
  interval: 1h
  dependsOn:
    - name: keda
      namespace: observability
  path: ./kubernetes/apps/system/volsync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopia
  namespace: &namespace system
spec:
  interval: 1h
  components:
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/ext-auth
    - ../../../../components/ext-auth/two
  dependsOn:
    - name: keda
      namespace: observability
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./kubernetes/apps/system/volsync/kopia
  postBuild:
    substitute:
      APP: *app
      EXT_AUTH_TARGET_2: kopia-s3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia-maintenance
  namespace: &namespace system
spec:
  interval: 1h
  dependsOn:
    - name: volsync
      namespace: system
  path: ./kubernetes/apps/system/volsync/maintenance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
