---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.envoyproxy.io/envoypatchpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: &name internal-root
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: *name
  type: JSONPatch
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/internal-root/https
      operation: &operation
        op: add
        jsonPath: ..filters[*].typed_config.http_filters[?(@.name=="envoy.filters.http.compressor.zstd")].typed_config
        value:
          '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
          choose_first: true
          compressor_library:
            name: envoy.compression.zstd.compressor
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.compression.zstd.compressor.v3.Zstd
          response_direction_config:
            remove_accept_encoding_header: true
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/internal-root/https-quic
      operation: *operation
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.envoyproxy.io/envoypatchpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: &name internal
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: *name
  type: JSONPatch
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/internal/https
      operation: &operation
        op: add
        jsonPath: ..filters[*].typed_config.http_filters[?(@.name=="envoy.filters.http.compressor.zstd")].typed_config
        value:
          '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
          choose_first: true
          compressor_library:
            name: envoy.compression.zstd.compressor
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.compression.zstd.compressor.v3.Zstd
          response_direction_config:
            remove_accept_encoding_header: true
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/internal/https-quic
      operation: *operation
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.envoyproxy.io/envoypatchpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: &name external
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: *name
  type: JSONPatch
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/external/https
      operation: &operation
        op: add
        jsonPath: ..filters[*].typed_config.http_filters[?(@.name=="envoy.filters.http.compressor.zstd")].typed_config
        value:
          '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
          choose_first: true
          compressor_library:
            name: envoy.compression.zstd.compressor
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.compression.zstd.compressor.v3.Zstd
          response_direction_config:
            remove_accept_encoding_header: true
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/external/https-quic
      operation: *operation
