---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.2.0/schemas/config-schema.json
sonarr:
  series:
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true

    media_management:
      propers_and_repacks: do_not_prefer

    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: c4cadd6b35b95f62c3d47a408e53e2f7 # WEB-2160p (Combined)
        reset_unmatched_scores:
          enabled: true
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      - trash_ids: # only do a minor penalty, instead of the default major one
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-2160p (Combined)
            score: -100
          - name: Remux-1080p
            score: -100

      - trash_ids: # only do a minor penalty, instead of the default major one
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
        assign_scores_to:
          - name: WEB-2160p (Combined)
            score: -100
          - name: Remux-1080p
            score: -100

      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
        assign_scores_to:
          - name: WEB-2160p (Combined)

      # anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p
            score: 1000 # Adjust scoring as desired
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p
            score: 0 # Adjust scoring as desired
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p
            score: 2000 # Adjust scoring as desired

radarr:
  movies:
    base_url: http://radarr.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true

    media_management:
      propers_and_repacks: do_not_prefer

    include:
      # SQP
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-custom-formats-sqp-1-2160p
      - template: radarr-quality-profile-sqp-1-2160p-default
      # anime
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-anime-tmdb

    quality_definition:
      type: sqp-uhd

    quality_profiles:
      - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # [SQP] SQP-1 (1080p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      - trash_ids:
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)

      - trash_ids: # only do a minor penalty, instead of the default major one
          - dc98083864ea246d05a42df0d05f81cc # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: -100
          - name: Remux-1080p
            score: -100

      - trash_ids: # only do a minor penalty, instead of the default major one
          - cae4ca30163749b891686f95532519bd # AV1
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: -500
          - name: Remux-1080p
            score: -500

      # anime
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p
            score: 1000 # Adjust scoring as desired
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p
            score: 0 # Adjust scoring as desired
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p
            score: 2000 # Adjust scoring as desired
