---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tholinka-dev-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: tholinka-dev-tls
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: '*.tholinka.dev,tholinka.dev'
          cert-manager.io/certificate-name: tholinka-dev
          cert-manager.io/common-name: ''
          cert-manager.io/ip-sans: ''
          cert-manager.io/issuer-group: ''
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt
          cert-manager.io/uri-sans: ''
        labels:
          controller.cert-manager.io/fao: 'true'
  dataFrom:
    - extract:
        key: lets_encrypt_tls
        decodingStrategy: Base64
