---
# yaml-language-server: $schema=https://schemas.tholinka.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: tholinka
  namespace: renovate
spec:
  discoveryFilter: tholinka/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: 'true'
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: &d dockerhub
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: *d
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"}]
    - name: RENOVATE_REDIS_URL
      value: redis://dragonfly-cluster.database.svc.cluster.local:6379/4
    - name: RENOVATE_REPOSITORY_CACHE
      value: enabled
    - name: RENOVATE_CACHE_PRIVATE_PACKAGES
      value: 'true'
  image: ghcr.io/renovatebot/renovate:43.0.5
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: lab-assistant-tholinka
  webhook:
    enabled: true
    authentication:
      enabled: false
