---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-${APP}
  namespace: postgres
spec:
  name: ${APP}
  owner: ${OWNER}
  cluster:
    name: postgres-cluster
  extensions: ${EXTENSIONS:=${emptyArray}}
