---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kopia
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    ignore:
      - paths: [/spec/replicas]
  values:
    controllers:
      *app : &controller
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app: &container
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.0@sha256:aa6a2f5987b9c991a349c34e0c7ef80f00366d84490d7637355b10d38fcbc034
            env:
              KOPIA_WEB_ENABLED: true
              KOPIA_WEB_PORT: &port 80
            envFrom:
              - secretRef:
                  name: *app
            args:
              - --without-password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
      s3:
        <<: *controller
        replicas: 0 # normally 0 replicas, can manually increase when needed
        containers:
          app:
            <<: *container
            envFrom:
              - secretRef:
                  name: '{{ .Release.Name }}-s3'

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      s3: &service
        controller: s3
        ports:
          http:
            port: *port
      app:
        <<: *service
        controller: *app
        forceRename: *app

    route:
      s3: &route
        hostnames: ['{{ .Release.Name }}-s3.${SECRET_DOMAIN}']
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs: [{ identifier: s3 }]
        annotations: &routeAnnotations
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/name: Kopia S3
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/icon: kopia.svg
      app:
        <<: *route
        forceRename: *app
        hostnames: ['{{ .Release.Name }}.${SECRET_DOMAIN}']
        rules:
          - backendRefs: [{ identifier: app }]
        annotations:
          <<: *routeAnnotations
          gethomepage.dev/name: Kopia

    persistence:
      config-file:
        type: configMap
        name: kopia-repository-configmap
        advancedMounts:
          *app :
            app:
              - path: /config/repository.config
                subPath: repository.config
                readOnly: true
      config-file-s3:
        type: secret
        name: kopia-s3
        advancedMounts:
          s3:
            app:
              - path: /config/repository.config
                subPath: repository.config
                readOnly: true

      repository:
        type: nfs
        server: nas.servers.internal
        path: /backups/VolsyncKopia
        globalMounts:
          - path: /repository

      tmpfs:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              - path: /config/cache
                subPath: cache
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
          s3:
            app:
              - path: /config/cache
                subPath: cache-s3
              - path: /config/logs
                subPath: logs-s3
              - path: /tmp
                subPath: tmp-s3
