---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-db
  namespace: &namespace database
spec:
  dependsOn:
    - name: cnpg
      namespace: database
  interval: 1h
  path: ./kubernetes/components/cnpg/db/ks/db
  postBuild:
    substitute:
      APP: ${APP}
      OWNER: ${DATABASE_OWNER:=${APP}}
      EXTENSIONS: ${q:='}${DATABASE_EXTENSIONS}${q:='}

      emptyArray: '[]'
  healthChecks:
    - name: postgres-${APP}
      namespace: *namespace
      kind: Database
      apiVersion: postgresql.cnpg.io/v1
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
