---
originRequest:
  http2Origin: true
  keepAliveTimeout: 3600s
  originServerName: external.tholinka.dev
  tcpKeepAlive: 7200s

ingress:
  - hostname: tholinka.dev
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: '*.tholinka.dev'
    service: *svc
  - service: http_status:404
