---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./descheduler/ks.yaml
  - ./fstrim/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./irqbalance/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./volsync/ks.yaml
components:
  - ../../components/common
  - ../../components/repos/app-template
