---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: &namespace security
spec:
  interval: 1h
  path: ./kubernetes/apps/security/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: &namespace security
spec:
  interval: 1h
  path: ./kubernetes/apps/security/external-secrets/store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  dependsOn:
    - name: external-secrets
  postBuild:
    substituteFrom:
      - kind: Secret
        name: bitwarden
        optional: false
  healthChecks:
    - apiVersion: &certApiVersion cert-manager.io/v1
      kind: &certKind Certificate
      name: bitwarden-tls-certs
      namespace: *namespace
    - apiVersion: &secretApiVersion external-secrets.io/v1
      kind: &secretKind ClusterSecretStore
      name: bitwarden
  healthCheckExprs:
    - apiVersion: *certApiVersion
      kind: *certKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
    - apiVersion: *secretApiVersion
      kind: *secretKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
