---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret flux-operator-web-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    template:
      data:
        config.yaml: |
          apiVersion: web.fluxcd.controlplane.io/v1
          kind: Config
          spec:
            authentication:
              impersonation:
                username: claims.preferred_username
              oauth2:
                clientID: '{{ .FLUX_WEB_CLIENT_ID }}'
                clientSecret: '{{ .FLUX_WEB_CLIENT_SECRET }}'
                issuerURL: https://auth.tholinka.dev/application/o/flux-operator/
                provider: OIDC
              type: OAuth2
            baseURL: https://flux-operator.tholinka.dev
  dataFrom:
    - extract:
        key: flux
