---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-operator
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Flux Operator
    gethomepage.dev/icon: flux-cd.svg
spec:
  hostnames:
    - flux-operator.tholinka.dev
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: flux-operator
          namespace: flux-system
          port: 9080
