---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  # kopia can't actually successfully restore automatically because kopia doesn't backup xattrs (https://github.com/kopia/kopia/issues/544),
  # but the files are still present for a manual restore
  - ../../../../components//volsync/local/externalsecret.yaml
  - ../../../../components/volsync/local/replicationsource.yaml
  - ../../../../components/volsync/remote
configMapGenerator:
  - name: opencloud
    files:
      - csp.yaml=./config/csp.yaml
configurations:
  - ./config/kustomizeconfig.yaml
