---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: *name
    template:
      data:
        BITWARDEN_ORGANIZATION_ID: '{{ .BITWARDEN_ORGANIZATION_ID }}'
        BITWARDEN_PROJECT_ID: '{{ .BITWARDEN_PROJECT_ID }}'
        BITWARDEN_MACHINE_KEY: '{{ .BITWARDEN_MACHINE_KEY }}'
  dataFrom:
    - extract:
        key: *name
